[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "package"
version = "0.0.1"
description = "Library and CLI to extract structured data from german organigrams"
readme = "README.md"
authors = []

[project.scripts]
cli = "src.__main__:main"