[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "organigram_extract"
version = "0.0.1"
requires-python = ">= 3.12"
dependencies = [
    "pymupdf>=1",
    "spacy",
    "llm",
    "fix-busted-json",
]
